engine/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Json;
use app\components\AccessRule;
use app\components\MyFormatter;
use app\models\AgentLoginForm;
use app\models\ContactForm;
use app\models\Agent;
use app\models\User;
use app\models\Role;
use app\models\Property;
use app\models\PropertyNews;
use app\models\PropertySearch;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    // public function behaviors()
    // {
    //     return [
    //         'access' => [
    //             'class' => AccessControl::className(),
    //             'ruleConfig' => [
    //                 'class' => AccessRule::className(),
    //             ],
    //             'rules' => [
    //                 [
    //                     'actions' => ['login', 'logout'],
    //                     'allow' => true,
    //                 ],
    //                 // [
    //                 //     'actions' => ['logout'],
    //                 //     'allow' => true,
    //                 //     'roles' => ['@'],
    //                 // ],
    //             ],
    //         ],
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'logout' => ['post'],
    //             ],
    //         ],
    //     ];
    // }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionSearch()
    {
        $searchModel = new PropertySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataDistrict = Property::getAllDistrict();
        $dataType = Property::getAllType();
        $dataStatus = Property::getAllStatus();

        return $this->render('search_result', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dataDistrict' => $dataDistrict,
            'dataType' => $dataType,
            'dataStatus' => $dataStatus,
        ]); 
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        // if (Yii::$app->agent->isGuest == true) {
            // return $this->redirect(['site/login']);
        // } else {
            // return $this->redirect(['agents/profile']);
        // }
        // $id = Yii::$app->agent->id;
        $searchModel = new PropertySearch();
        $model = new ContactForm();
        $dataProvider = new ActiveDataProvider([
            'query' => PropertyNews::find()->joinWith('property p')->where(['not in', 'p.status', Property::STATUS_DELETED]),
            'sort' => ['defaultOrder' => ['created_at' => SORT_DESC]],
            'pagination' => [
                'defaultPageSize' => 5,
            ],
        ]);
        $dataDistrict = Property::getAllDistrict();
        $dataType = Property::getAllType();
        $dataStatus = Property::getAllStatus();
        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'dataDistrict' => $dataDistrict,
            'dataType' => $dataType,
            'dataStatus' => $dataStatus,
        ]);
    }

    public function actionAboutUs()
    {
        return $this->render('about_us');
    }

    public function actionContactUs()
    {
        $model = new ContactForm();

        if ($model->load(Yii::$app->request->post())) {
            $emailto = [Yii::$app->params['admin.email'], $model->email];
            if ($model->contactUs($emailto)) {
                Yii::$app->session->setFlash('contactFormSubmitted');

                return $this->refresh();
            }
        }
        return $this->render('contact_us', [
            'model' => $model,
        ]);
    }

    public function actionDetail()
    {
        return $this->render('detail');
    }

    public function actionAgentsdetail()
    {
        return $this->render('agents_detail');
    }

    public function actionProperty()
    {
        return $this->render('property');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $modelUser = new User();
        $modelAgent = new Agent();
        
        if (!Yii::$app->agent->isGuest) {
            return $this->goHome();
        }

        $model = new AgentLoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['agents/profile']);
        }

        if ($modelAgent->load(Yii::$app->request->post())) {
            // die(var_dump($_POST));
            // $modelUser->password = md5($modelUser->password);
            // $modelUser->id_role = Role::ROLE_AGENT;
            // $modelUser->created_at = date('Y-m-d H:i:s');
            // if ($modelUser->validate()) {
                // if ($modelUser->save()) {
                    $modelAgent->password = md5($modelAgent->password);
                    $modelAgent->confirm_password_login = md5($modelAgent->password);
                    $modelAgent->created_at = date('Y-m-d H:i:s');
                    if ($modelAgent->validate() && $modelAgent->save()) {
                        Yii::$app->session->setFlash('info', MyFormatter::success('<strong>Congrats!</strong> Data is successfully saved.'));
                        return $this->refresh();
                    }
                // }
            // }
        }

        return $this->render('login', [
            'model' => $model,
            'modelUser' => $modelUser,
            'modelAgent' => $modelAgent,
        ]);
    }

    public function actionLoginprocess()
    {
        $model = new AgentLoginForm();

        // if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
        //     Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        //     return ActiveForm::validate($model);
        // }

        if (Yii::$app->request->isAjax && Yii::$app->request->post()) {
            $post = Yii::$app->request->post();
            $data = [
                "_csrf" => $post["_csrf"],
                "AgentLoginForm" => $post,
            ];
            // die(var_dump($model->load($data)));
            // die(var_dump($model->login()));
            if ($model->load($data) && $model->login()) {
                // login success
                $message = ["result" => true, "redirectUrl" => Url::to(['agents/profile'])];
                Yii::$app->response->format = Response::FORMAT_JSON; 
                return $message;
            } else {
                // login failure
                $message = ["result" => false];
                Yii::$app->response->format = Response::FORMAT_JSON; 
                return $message;
            }
        } else {
            $message = ["result" => false];
            Yii::$app->response->format = Response::FORMAT_JSON; 
            return $message;
        }
    }

    public function actionRegister()
    {
        $modelUser = new User();
        $modelAgent = new Agent();
        
        if (!Yii::$app->agent->isGuest) {
            return $this->goHome();
        }

        $model = new AgentLoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['agents/profile']);
        }

        if ($modelAgent->load(Yii::$app->request->post())) {
            // die(var_dump($_POST));
            // $modelUser->password = md5($modelUser->password);
            // $modelUser->id_role = Role::ROLE_AGENT;
            // $modelUser->created_at = date('Y-m-d H:i:s');
            // if ($modelUser->validate()) {
                // if ($modelUser->save()) {
                    $modelAgent->password = md5($modelAgent->password);
                    $modelAgent->confirm_password_login = md5($modelAgent->password);
                    $modelAgent->created_at = date('Y-m-d H:i:s');
                    if ($modelAgent->validate() && $modelAgent->save()) {
                        Yii::$app->session->setFlash('info', MyFormatter::success('<strong>Congrats!</strong> Data is successfully saved.'));
                        return $this->refresh();
                    }
                // }
            // }
        }

        return $this->render('register', [
            'model' => $model,
            'modelUser' => $modelUser,
            'modelAgent' => $modelAgent,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->agent->logout();

        // return $this->goHome();
        return $this->redirect(['site/index']);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        $id = Yii::$app->agent->id;
        $agent = $this->findAgent($id);
        $email_agent = '';
        if (!Yii::$app->agent->isGuest) {
            $email_agent = $agent->email;
        }
        $emailto = [Yii::$app->params['admin.email'], $email_agent];
        if ($model->load(Yii::$app->request->post()) && $model->contact($emailto)) {
            Yii::$app->session->setFlash('contactFormSubmitted');

engine/views/layouts-old/_footer.php
<footer class="footer-main">
    <!-- <div class="footer-info">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 pb-lg-0 pb-3">
                    <h4>About Us</h4>
                    <p>
                        Lorem ipsum dolor sit amet, consectet ur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup
                    </p>
                    <p>
                        tate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed u
                    </p>
                    <a href="#">Read more</a>
                </div>
                <div class="col-lg-4 pb-lg-0 pb-3">
                    <h4>Recent Blog Posts</h4>
                    <ul class="blog-posts">
                        <li>
                            Quisque sit amet sollicitudin augue. Sed dui quam, molestie at semper vitae, sagittis eu justo.
                            <b>22nd May 2013</b>
                        </li>
                        <li>
                            Quisque sit amet sollicitudin augue. Sed dui quam, molestie at semper vitae, sagittis eu justo.
                            <b>22nd May 2013</b>
                        </li>
                        <li>
                            Quisque sit amet sollicitudin augue. Sed dui quam, molestie at semper vitae, sagittis eu justo.
                            <b>22nd May 2013</b>
                        </li>
                    </ul>
                    <a href="#">Read more</a>
                </div>
                <div class="col-lg-4 pb-lg-0 pb-3">
                    <h4>Contact Information</h4>
                    <ul class="contact-list">
                        <li><span class="pr-2">P |</span>(123) 456 7980</li>
                        <li><span class="pr-2">P |</span>Namehere@gmail.com</li>
                        <li><span class="pr-2">P |</span>www.namehere.com</li>
                        <li><span class="pr-2">P |</span>501 Your Street to go here</li>
                    </ul>
                    <h4>Newsletter Sign-up</h4>
                    <form action="#" class="newsletter d-flex align-items-center">
                        <input type="text" class="form-control" name="newsletter" placeholder="Enter your email here">
                        <div class="input-group-prepend">
                            <button class="input-group-text">
                                Subscribe
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div> -->

    <div class="footer-copyright bg-dark footer-p">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 pb-lg-0 pb-3">
                    Copyright © <?= date('Y'); ?>.  PropInside. All right Reserved.
                </div>
                <div class="col-lg-4 pb-lg-0 pb-3">
                    <ul class="d-flex align-items-center">
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms of Use</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 pb-lg-0 pb-3 d-flex align-items-center">
                    <p style="color: #fff; font-size: 12px;">Connect with us:</p>
                    <ul class="pl-2 d-flex">
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

engine/views/layouts-old/_header.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use app\components\MyFormatter;
use yii\widgets\ActiveForm;
use app\models\AgentLoginForm;

$model = new AgentLoginForm();
?>

<header class="header-main border-bottom-5-blue">
    <div class="header-topbar d-flex align-items-center justify-content-center text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h5>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    </h5>
                </div>
            </div>
        </div>
    </div>
    <div class="header-menu d-flex align-items-center justify-content-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-3 d-flex align-items-center">
                    <div class="site-logo">
                        <a href="<?= Url::home(); ?>"><img src="<?= Url::base(); ?>/assets/img/logo.png" alt="logo" class="mw-100"></a>
                    </div>
                </div>
                <div class="col-lg-7 d-none d-lg-flex align-items-center justify-content-center">
                    <nav>
                        <ul id="phn-menu" class="site-menu d-flex">
                            <li><a href="<?= Url::home(); ?>" class="<?= MyFormatter::active(['site'], 'a'); ?>">Upcoming & New Launches</a></li>
                            <li><a href="<?= Url::to(['/agents']); ?>" class="<?= MyFormatter::active(['agents'], 'c'); ?>">Agents</a></li>
                            <li><a href="<?= Url::to(['/site/about-us']); ?>" class="<?= MyFormatter::active(['site/about-us'], 'a'); ?>">About Us</a></li>
                            <li><a href="<?= Url::to(['/site/contact-us']); ?>" class="<?= MyFormatter::active(['site/contact-us'], 'a'); ?>">Contact Us</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3 col-9 d-flex align-items-center justify-content-end">
                    <i class="pr-3"><img src="<?= Url::base(); ?>/assets/img/icons/lock.jpg" alt="lock" class="mw-100"></i>
                    <ul class="log-link d-flex">
                        <?php if (Yii::$app->agent->identity == null) { ?>
                        <!-- <li><a href="<?//= Url::to(['/site/login']); ?>">Login</a></li> -->
                        <li>
                            <a class="pgicon pgicon-user" href="#" title="Log In" id="modal-login-nav" data-toggle="modal" data-target="#modal-login">
                                <span class="hidden-xs hidden-sm">Log In </span>
                            </a>
                        </li>
                        <li>
                            <a class="header-ab-test pgicon pgicon-users hidden-xs hidden-sm" href="<?= Url::to(['site/register']); ?>" title="Sign Up" id="modal-login-nav">
                                <span class="hidden-xs hidden-sm">Sign Up</span>
                            </a>
                        </li>
                        <?php } else { ?>
                        <li>
                            <?= Html::a('Logout', ['site/logout'],[
                                    'data'=>[
                                        'method'=>'post'
                                    ]
                                ]);
                            ?>
                        </li>
                        <li>
                            <a class="header-ab-test pgicon pgicon-user hidden-xs hidden-sm" href="<?= Url::to(['agents/profile']); ?>" title="Sign Up" id="modal-login-nav" style="margin-left: 20px;">
                                <span class="hidden-xs hidden-sm"><?= Yii::$app->agent->identity->name; ?></span>
                            </a>
                        </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="modal modal-user-box" id="modal-login" tabindex="-1" role="dialog" aria-labelledby="modal-login-title" aria-hidden="true" data-backdrop="static">
    <?php $form = ActiveForm::begin([
        'action' => 'javascript:;',
        'id' => 'login_form',
        'enableClientValidation' => true,
        // 'enableAjaxValidation' => true,
        'options' => [
            'class' => 'form-horizontal modal-form',
            'role' => 'form',
            'method' => 'POST',
            'name' => 'login_form',
            // 'onsubmit' => 'handle(event)',
        ],
    ]); ?>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="modal-login-title" style="margin: 0 75px;">Login to <br>PropInside Website</h3>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="login-wrapper">
                            <div class="alert alert-danger alert-dismissable hide" id="login-error-message">
                                There seems to be an issue on our end. Please try again later
                            </div>
                            <?php $fieldOptionsUsername = [
                                'options' => ['class' => 'form-group'],
                                'template' => '<i class="pgicon pgicon-user-o"></i>{input}<span class="error-msg">{error}</span>',
                            ]; ?>
                            <?= $form->field($model, 'username', $fieldOptionsUsername)->textInput(['id'=>'login-userid', 'class'=>'form-control', 'placeholder'=>'Username', 'autocomplete'=>'off'])->label(false) ?>

                            <?php $fieldOptionsPassword = [
                                'options' => ['class' => 'form-group'],
                                'template' => '<i class="pgicon pgicon-key"></i>{input}<span class="error-msg">{error}</span>',
                            ]; ?>
                            <?= $form->field($model, 'password', $fieldOptionsPassword)->passwordInput(['id'=>'login-password', 'class'=>'form-control', 'placeholder'=>'Password', 'autocomplete'=>'off'])->label(false) ?>
                            <div class="actions">
                                <div class="pull-left stay-login">
                                    <label class="checkbox">
                                        <input name="remember_me" type="checkbox" checked="checked" value=""> Remember Me
                                    </label>
                                </div>
                            </div>
                            <div class="actions">
                                <?= Html::button('Log In', ['id' => 'btn_login', 'name' => 'btn_login', 'class' => 'btn btn-primary btn-md', 'style' => 'width:100%;', 'onclick' => 'LoginDo(); return false;']) ?>
                                <p class="orLabel"><span>Or</span></p>
                            </div>
                            <div class="actions socialNetLogin">
                                <a id="link-facebook-modal-login" class="btn btn-main btn-md pgicon pgicon-facebook pull-left" href="#" disabled>Facebook</a>
                                <a id="link-google-modal-login" class="btn btn-grey btn-md btn-img-google-icon" href="#" disabled>Google</a>
                            </div>
                        
                    </div>
                </div>
                <div class="modal-footer" style="justify-content:center;">
                    <p>Don't have an account? <a id="link-sign-up-modal-login" href="<?= Url::to(['site/register']); ?>" title="Sign Up" target="_blank">Sign Up</a></p>
                    <!-- <p>Are you an agent? <a id="link-login-agentnet-modal-login" href="http://agentnet.propertyguru.com.sg" alt="Log In to AgentNet">Log In to AgentNet</a></p> -->
                </div>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
    <!-- </form> -->
</div>

engine/views/layouts-old/blank.php
<?=$content?>

engine/views/layouts-old/main.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);

$this->title = 'Homepage';
$theme = Url::base().'/assets';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- site meta -->
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="title" content="p1-property" />
        <meta name="description" content="p1-property">
        <meta name="keywords" content="p1-property, study, TEFL">
        <meta name="author" content="p1-property">

        <!-- site favicon -->
        <link rel="icon" href="<?= $theme; ?>/favicon.png" type="image/png">

        <!-- site title -->
        <title>Prop Inside - <?= $this->title; ?></title>
        <?php $this->head() ?>
        <link href="<?= $theme; ?>/castle/css/style.css" rel="stylesheet" type="text/css" />
        <link href="<?= $theme; ?>/castle/css/search.css" rel="stylesheet" type="text/css" />
        <link href="<?= $theme; ?>/castle/css/reality-icon.css" rel="stylesheet" type="text/css" />
        <link href="<?= $theme; ?>/lightslider/css/lightslider.css" rel="stylesheet" type="text/css" />
        <link href="<?= $theme; ?>/lightgallery/css/lightgallery.css" rel="stylesheet" type="text/css" />
        <!-- <link href="<?= $theme; ?>/lightslider/css/custom-lightslider.css" rel="stylesheet" type="text/css" /> -->
        <link href="<?= $theme; ?>/propertyguru/css/desktop.css" rel="stylesheet" type="text/css" />
        <link href="<?= $theme; ?>/metronic/global/plugins/bootstrap-sweetalert/sweetalert.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="<?= $theme; ?>/castle/css/owl.carousel.css">
        <link rel="stylesheet" type="text/css" href="<?= $theme; ?>/castle/css/owl.transitions.css">
        <!-- ==== HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries ==== -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style type="text/css">
        .lg-backdrop.in {
            opacity: 0.85;
        }
        .fixed-size.lg-outer .lg-inner {
          background-color: #FFF;
        }
        .fixed-size.lg-outer .lg-sub-html {
          position: absolute;
          text-align: left;
        }
        .fixed-size.lg-outer .lg-toolbar {
          background-color: transparent;
          height: 0;
        }
        .fixed-size.lg-outer .lg-toolbar .lg-icon {
          color: #FFF;
        }
        .fixed-size.lg-outer .lg-img-wrap {
          padding: 12px;
        }
        .select2-search__field {
            font-size: 14px !important;
        }
        .select2-selection__placeholder {
            font-size: 14px !important;
        }
        .select2-selection__rendered {
            font-size: 14px !important;
        }
        .select2-selection__choice {
            font-size: 14px !important;
        }
        .select2-selection__clear {
            top: 4px !important;
        }
        .select2-selection__choice__remove {
            margin: -2px 0 0 3px !important;
        }
        .no-result {
            height: 400px;
        }
        </style>
    </head>
    <body>
        <?php $this->beginBody() ?>
        <!-- start site header -->
        <?php require_once('_header.php') ?>
        <!-- end site header -->

        <!-- start content -->
        <?= $content ?>
        <!-- end content -->

        <!-- start footer -->
        <?php require_once('_footer.php') ?>
        <script src="<?= $theme; ?>/lightslider/js/lightslider.js" type="text/javascript"></script>
        <script src="<?= $theme; ?>/lightgallery/js/lightgallery-all.min.js" type="text/javascript"></script>
        <script src="<?= $theme; ?>/metronic/global/plugins/bootstrap-sweetalert/sweetalert.min.js" type="text/javascript"></script>
        <script src="<?= $theme; ?>/castle/js/owl.carousel.min.js"></script> 
        <!-- end footer -->
        <?php $this->endBody() ?>
        <script type="text/javascript">
        jQuery(function($) {
            // "use strict";
            // ********* Check Box 
            $('input[name="radio-btn"]').wrap('<div class="radio-btn"><i></i></div>');
            $(".radio-btn").on("click", function() {
            var _this = $(this),
                block = _this.parent().parent();
                block.find('input:radio').attr('checked', false);
                block.find(".radio-btn").removeClass('checkedRadio');
                _this.addClass('checkedRadio');
                _this.find('input:radio').attr('checked', true);
            });
            // $('input[type="checkbox"]').wrap('<div class="check-box"><i></i></div>');
            $.fn.toggleCheckbox = function() {
                this.attr('checked', !this.attr('checked'));
            }
            $('.check-box').on("click", function() {
                $(this).find(':checkbox').toggleCheckbox();
                $(this).toggleClass('checkedBox');
            });

            $(".advanced").on("click", function() {
                $(".opened").slideToggle();
                return false;
            });

            $('.imageGallery').lightSlider({
                gallery:true,
                item: 1,
                loop: true,
                thumbItem: 9,
                slideMargin: 0,
                enableDrag: false,
                // currentPagerPosition:'left',
                width: '700px',
                height: '170px',
                addClass: 'fixed-size',

                thumbItem: 10,
                pager: true,
                gallery: false,
                galleryMargin: 5,
                thumbMargin: 5,
                currentPagerPosition: 'middle',
                onSliderLoad: function(el) {
                    // console.log("el :: ", el);
                    el.lightGallery({
                        selector: '.imageGallery .lslide',
                    });
                }
            });

            $('.propGallery').lightSlider({
                auto: true,
                gallery:true,
                item: 1,
                loop: true,
                thumbItem: 5,
                slideMargin: 0,
                enableDrag: false,

                pager: true,
                gallery: false,
                galleryMargin: 5,
                thumbMargin: 5,
                currentPagerPosition: 'middle',
                onSliderLoad: function(el) {
                    el.lightGallery({
                        selector: '.propGallery .lslide',
                    });
                },
            });

            $("#agent-2-slider").owlCarousel({
                autoPlay: false,
                stopOnHover: true,
                navigation: true,
                navigationText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>"],
                slideSpeed: 300,
                pagination: false,
                singleItem: true
            });
        });

        // function handle(e){
        //     e.preventDefault(); // Otherwise the form will be submitted
        //     LoginDo();
        // }
        $('#login-password').on("keypress", function (e) {
            if (e.keyCode == 13) {
                LoginDo();
            }
        });

        function LoginDo() {
            var url = "<?= Url::to(['/site/loginprocess']); ?>";
            var username = document.getElementById('login-userid').value;
            var pass = document.getElementById('login-password').value;
            var csrf = $('[name="_csrf"]').val();

            $.ajax({
                url: url,
                type: "POST",
                data: {username: username, password: pass, _csrf: csrf},
                dataType: "json",
                success: function(data) {
                    if (data.result == false) {
                        swal({ title: "Error!", text: "Incorrect username or password. Or the user is not yet approved by Administrator.", type: "error" });
                        // alert("Error");
                    } else {
                        // console.log(data);
                        window.location = data.redirectUrl;
                    }
                }
            });
        };

        function addAlert() {
          swal({ title: "Attention!", text: "Property Data that can be submitted only 5. Please check again in your Properties List.", type: "warning" });
        };
        </script>
    </body>
</html>
<?php $this->endPage() ?>