engine/controllers/AgentsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Agent;
use app\models\ContactForm;
use app\models\Property;
use app\models\PropertyImage;
use app\models\PropertyListing;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\components\AccessRule;
use app\components\MyFormatter;
use yii\db\Expression;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * AgentController implements the CRUD actions for Agent model.
 */
class AgentsController extends Controller
{
    const PROPS_PER_PAGE = 5;

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // 'ruleConfig' => [
                //     'class' => AccessRule::className(),
                // ],
                'only' => ['profile', 'my-properties', 'submit-property', 'upload', 'remove-prop-image'],
                'rules' => [
                    [
                        'actions' => ['profile', 'my-properties', 'submit-property', 'upload', 'remove-prop-image'],
                        'allow' => true,
                        // 'roles' => ['@'],
                        // 'roles' => ['$agent->getIsAgent'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        if ($action->id !== "upload") {
            $this->enableCsrfValidation = false;
        } elseif ($action->id !== "remove-prop-image") {
            $this->enableCsrfValidation = false;
        } else {
            $this->enableCsrfValidation = true;
        }
        // $this->enableCsrfValidation = ($action->id !== "upload");
        return parent::beforeAction($action);
    }

    /**
     * Lists all Agent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Agent::find()->where('is_approved=:app', [':app'=>Agent::STATUS_APPROVED]),
            'sort' => ['defaultOrder' => ['created_at' => SORT_DESC]],
            'pagination' => [
                'defaultPageSize' => 3,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionProfile()
    {
        // die(var_dump(Yii::$app->agent->isAgent));
        if (Yii::$app->agent->isGuest == true) {
            return $this->redirect(['/site/login']);
        } else {
            $id = Yii::$app->agent->id;
            $model = $this->findModel($id);
            $propCount = PropertyListing::find()
                ->where('id_agent=:id', [':id'=>$id])
                ->count();

            if ($model->load(Yii::$app->request->post())) {
                if ($model->new_password != NULL && $model->confirm_password != NULL) {
                    $model->password = md5($model->new_password);
                }
                if ($model->save()) {
                    Yii::$app->session->setFlash('info', MyFormatter::success('<strong>Congrats!</strong> Data is successfully saved.'));
                    return $this->refresh();
                }
            }

            return $this->render('profile', [
                'model' => $model,
                'propCount' => $propCount,
            ]);
        }
        
    }

    public function actionProperty($slug)
    {
        // if (Yii::$app->agent->isGuest == true) {
            // return $this->redirect(['site/login']);
        // } else {
            $model = $this->findPropertyBySlug($slug);
            $modelContact = new ContactForm();

            return $this->render('detail_property', [
                'model' => $model,
                'modelContact' => $modelContact,
            ]);
        // }
    }

    public function actionMyProperties()
    {
        if (Yii::$app->agent->isGuest == true) {
            return $this->redirect(['site/login']);
        } else {
            $id = Yii::$app->agent->id;
            $agent = $this->findModel($id);
            $dataProvider = new ActiveDataProvider([
                'query' => PropertyListing::find()->joinWith('property')->where('id_agent=:id', [':id'=>$id])->andWhere(['not in', 'status', Property::STATUS_DELETED]),
                'sort' => ['defaultOrder' => ['id_property' => SORT_DESC]],
                'pagination' => [
                    'defaultPageSize' => self::PROPS_PER_PAGE,
                ],
            ]);

            return $this->render('properties', [
                'agent' => $agent,
                'dataProvider' => $dataProvider,
            ]);
        }

        
    }

    public function actionSubmitProperty()
    {
        if (Yii::$app->agent->isGuest == true) {
            return $this->redirect(['site/login']);
        } else {
            $id = Yii::$app->agent->id;
            $agent = $this->findModel($id);
            $property = new Property();
            $property_images = new PropertyImage();
            $property_listing = new PropertyListing();
            $uploadedImages = PropertyImage::find()
                ->where(['id_image' => \Yii::$app->session->get('new_images', [])])
                ->orderBy('sort_order ASC, id_image ASC')
                ->all();
            $dataDistrict = Property::getAllDistrict();
            $dataType = Property::getAllType();

            if ($property->load(Yii::$app->request->post())) {
                // die(var_dump($_POST['Property']['prop_facilities']));
                $property->created_at = date('Y-m-d H:i:s');
                if ($property->save()) {
                    $modelImages = $property_images->handleUploadedImages($property->id_property);
                    $property->saveFacilities($property->id_property, $_POST['Property']['prop_facilities']);
                    $property->saveAmenities($property->id_property, $_POST['Property']['prop_amenities']);
                    $property_listing->id_agent = $id;
                    $property_listing->id_property = $property->id_property;
                    $property_listing->created_at = date('Y-m-d H:i:s');
                    $property_listing->save();
                    Yii::$app->session->setFlash('info', MyFormatter::success('<strong>Congrats!</strong> Data is successfully saved.'));
                    return $this->refresh();
                }
            }

            return $this->render('submit_property', [
                'agent' => $agent,
                'property' => $property,
                'property_images' => $property_images,
                'dataDistrict' => $dataDistrict,
                'dataType' => $dataType,
            ]);
        }
    }

    public function actionUpload()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $error = null;
        $models = [];
        $images = new PropertyImage();

        $transaction = Yii::$app->db->beginTransaction();
        try {
            $models = $images->handleUploadedImages((int)Yii::$app->request->post('id', 0));
            $transaction->commit();

        } catch (\Exception $e) {
            $error = $e->getMessage() . ' at ' . $e->getFile() . ":" . $e->getLine() . PHP_EOL . $e->getTraceAsString();
            $transaction->rollBack();
        }

        if (!$error && $models) {
            $model = reset($models);
            $file_explode = explode('/', $model->image_path);
            $file_name = $file_explode[4];
            $resp = [
                'initialPreview' => [
                    Yii::getAlias('@web'.$model->image_path),
                ],
                'initialPreviewConfig' => [[
                    'caption' => $file_name,
                    'url' => Url::to(['/agents/remove-prop-image']),
                    'key' => $model->id_image
                ]]
            ];
        } else {
            $resp = ['error' => $error ? $error : ($images->hasErrors() ? $images->getFirstErrors() : 'Unknown')];
        }

        return $resp;
    }

    /**
     * @return array|Response
     */
    public function actionRemovePropImage()
    {
        /* allow only ajax calls */
        if (!Yii::$app->request->isAjax) {
            return $this->redirect(['agents/submit-property']);
        }

        /* set the output to json */
        Yii::$app->response->format = Response::FORMAT_JSON;

        $imageId = Yii::$app->request->post('key');
        if (empty($imageId)) {
            return ['result' => 'error', 'html' => Yii::t('app', 'Something went wrong...')];
        }

        $imageId = PropertyImage::findOne(['id_image' => $imageId]);
        if (empty($imageId)) {
            return ['result' => 'error', 'html' => Yii::t('app', 'Something went wrong...')];
        }

        // if all images are deleted then the prop is not active anymore
        // $countImages = PropertyImage::find()->where(['id_property' => $imageId->id_property])->count();
        // if ($countImages == 1) {
        //     $prop = Property::find()->where(['id_property' => $imageId->id_property])->one();
        //     $prop->status = Property::STATUS_NOT_ACTIVE;
        //     $prop->save(false);
        // }

        $imageId->delete();

        return ['result' => 'success', 'response' => $imageId];
    }

    /**
     * Displays a single Agent model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionDetail($id)
    {
        $model = $this->findModel($id);

engine/views/agents/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Agent */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="agent-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_user')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'photo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'registration_number')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'phone_number')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'award')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'speciality')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'country_operability')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'investment_deposit_range')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'facebook')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'twitter')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'linkedin')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'total_clicks')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

engine/views/agents/_list_agent.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

?>

<!-- agent-details-items -->
<div class="agent-details-items bg-white">
    <div class="row">
        <div class="col-sm-4">
            <div class="agent-details-img text-center mb-sm-0 mb-4">
                <?php if($model->photo != NULL) { ?>
                    <img src="<?= Yii::getAlias('@web').$model->photo; ?>" alt="agents" class="mw-100" width="200px" height="250px">
                <?php } else { ?>
                    <img src="<?= Yii::getAlias('@web/assets/propinside/img/team/t2.png'); ?>" alt="team" class="w-100">
                <?php } ?>
                <div class="d-flex justify-content-center mt-4">
                    <ul class="social-link d-flex align-items-center justify-content-center">
                        <li>
                            <?php if ($model->facebook != NULL) { ?>
                            <a href="<?= $model->facebook; ?>" class="d-flex align-items-center justify-content-center" target="_blank">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <?php } else { ?>
                            <a href="javascript:;" class="d-flex align-items-center justify-content-center" style="color: gray;">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <?php } ?>
                        </li>
                        <li>
                            <?php if ($model->twitter != NULL) { ?>
                            <a href="<?= $model->twitter; ?>" class="d-flex align-items-center justify-content-center" target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                            <?php } else { ?>
                            <a href="javascript:;" class="d-flex align-items-center justify-content-center" style="color: gray;">
                                <i class="fa fa-twitter"></i>
                            </a>
                            <?php } ?>
                        </li>
                        <li>
                            <?php if ($model->twitter != NULL) { ?>
                            <a href="<?= $model->linkedin; ?>" class="d-flex align-items-center justify-content-center" target="_blank">
                                <i class="fa fa-linkedin"></i>
                            </a>
                            <?php } else { ?>
                            <a href="javascript:;" class="d-flex align-items-center justify-content-center" style="color: gray;">
                                <i class="fa fa-linkedin"></i>
                            </a>
                            <?php } ?>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="agent-details-info">
                <h4><?= strtoupper($model->name); ?></h4>
                <p class="text-justify">
                    <?= $model->description != NULL ? $model->description : 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'; ?>
                </p>
                <ul class="d-sm-flex align-items-center justify-content-between mb-5">
                    <li><span class="text-info">Mobile :</span> <?= $model->phone_number; ?></li>
                    <li><span class="text-info">Office :</span> <?= $model->office != null ? $model->office : '-'; ?></li>
                    <li><span class="text-info">Fax :</span> <?= $model->fax != null ? $model->fax : '-'; ?></li>
                </ul>
                <div class="d-flex justify-content-start justify-content-sm-end">
                    <a href="<?= Url::to(['/agents/detail?id='.$model->id_agent]); ?>" class="btn btn-info MyriadPro d-inline-flex align-items-center justify-content-center px-4 mt-lg-5">
                        Learn More
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
<!-- agent-details-items -->

engine/views/agents/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Agent */

$this->title = 'Create Agent';
$this->params['breadcrumbs'][] = ['label' => 'Agents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="agent-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

engine/views/agents/profile.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
// use kartik\widgets\FileInput;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Agents Profile';
$theme = Url::base().'/assets/castle';
// $avatarImage = ($model->photo) ? Yii::getAlias('@web').$model->photo : Yii::getAlias('@web/assets/castle/images/default.jpg');
$avatarImage = ($model->photo) ? Yii::getAlias('@web').$model->photo : Url::base().'/assets/img/testimonial/7.png';
?>

<!-- agents profile page -->
<section id="agent-2-peperty" class="profile padding_half">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="f-p-links bottom30">
          <li><a href="#" class="active"><i class="icon-icons230"></i>Profile</a></li>
          <li><a href="<?= Url::to(['agents/my-properties']); ?>"><i class="icon-icons215"></i> My Properties</a></li>
          <li>
            <?php if ($propCount >= 5) { ?>
              <a href="#" onclick="addAlert()"><i class="icon-icons202"></i> Submit Property</a>
            <?php } else { ?>
              <a href="<?= Url::to(['agents/submit-property']); ?>"><i class="icon-icons202"></i> Submit Property</a>
            <?php } ?>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container-3">
    <div class="row">
      <?php $form = ActiveForm::begin([
        'id' => 'profile-form',
        'enableClientValidation' => true,
        'options' => [
              'class' => 'callus',
              'enctype'=>'multipart/form-data',
          ],
      ]); ?>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <h2 class="text-uppercase bottom30 text-center">my profile</h2>
        <?= Yii::$app->session->getFlash('info');?>
        <div class="agent-p-img">
          <!-- <img src="<?= $theme; ?>/images/profile.jpg" class="img-responsive" alt="image"> -->
          <!-- <a href="#" class="top10 bottom20">Update Profile Picture</a> -->
          <?= $form->field($model, 'photo')->widget(\kartik\file\FileInput::classname(), [
              'options' => [
                  'accept' => 'image/*',
                  'data-image'=>$avatarImage,
              ],
              'pluginOptions' => [
                  'overwriteInitial'=> true,
                  'maxFileSize'=> 1500,
                  'showClose'=> false,
                  'showRemove' => false,
                  'showCaption'=> false,
                  'showBrowse'=> false,
                  'browseOnZoneClick'=> true,
                  'removeLabel'=> '',
                  'removeIcon'=> '<i class="glyphicon glyphicon-remove"></i>',
                  'removeTitle'=> 'Cancel or reset changes',
                  'elErrorContainer'=> '.image-upload-error',
                  'msgErrorClass'=> 'alert alert-block alert-danger',
                  'defaultPreviewContent'=> '<img src="'.$avatarImage.'" alt="Your Avatar" style="width:160px"><h6 class="text-muted">' . \Yii::t('app','Click to change picture') . '</h6>',
                  'layoutTemplates'=> ['main2'=> '{preview} {remove} {browse}'],
                  'allowedFileTypes' => ["image"],
              ]
          ])->label(false); ?>
          <p class="text-center">Minimum 215px x 215px<span>*</span></p>
        </div>
      </div>
      <div class="col-md-8">
        <div class="profile-form">
          <div class="row">
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Your Name:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'name')->textInput(['class'=>'keyword-input', 'placeholder'=>'Full Name'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Mobile:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'phone_number')->textInput(['class'=>'keyword-input', 'placeholder'=>'(+01) 34 56 7890', 'type'=>'number'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Office:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'office')->textInput(['class'=>'keyword-input', 'placeholder'=>'(+01) 34 56 7890'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Fax:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'fax')->textInput(['class'=>'keyword-input', 'placeholder'=>'(+01) 34 56 7890'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Email Address:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'email')->textInput(['class'=>'keyword-input', 'placeholder'=>'bohdan@realtyhomes.com'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Gender:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'gender')->dropDownList($model->getAllGender(), ['style'=>'height:15% !important;'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Title:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'title')->textInput(['class'=>'keyword-input', 'placeholder'=>'Title'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Country:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'country_operability')->textInput(['class'=>'keyword-input', 'placeholder'=>'Country'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Speciality:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'speciality')->textInput(['class'=>'keyword-input', 'placeholder'=>'Speciality'])->label(false) ?>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>About:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <?= $form->field($model, 'description')->textarea(['class'=>'form-control', 'placeholder'=>'Write here something about yours'])->label(false) ?>
                </div>
              </div>
              <div class="col-md-12 col-sm-12 col-xs-12 text-right">
                <?= Html::submitButton('Save Changes', ['class' => 'btn-blue border_radius']) ?>
              </div>
            <?php ActiveForm::end(); ?>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-sm-6 col-xs-12 profile-form margin20">
        <h3 class="bottom30 margin20">My Social Network</h3>
        <div class="row">
          <?php $form = ActiveForm::begin([
            'id' => 'social-form',
            'enableClientValidation' => true,
            'options' => [
                  'class' => 'callus',
              ],
          ]); ?>
            <div class="col-sm-4">
              <div class="single-query">
                <label>Facebook:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <?= $form->field($model, 'facebook')->textInput(['class'=>'keyword-input', 'placeholder'=>'http://facebook.com'])->label(false) ?>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="single-query">
                <label>Twitter:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <?= $form->field($model, 'twitter')->textInput(['class'=>'keyword-input', 'placeholder'=>'http://twitter.com'])->label(false) ?>
              </div>
            </div>
            <!-- <div class="col-sm-4">
              <div class="single-query">
                <label>Google Plus:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <input type="text" placeholder="http://google-plus.com" class="keyword-input">
              </div>
            </div> -->
            <div class="col-sm-4">
              <div class="single-query">
                <label>Linkedin:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <?= $form->field($model, 'linkedin')->textInput(['class'=>'keyword-input', 'placeholder'=>'http://linkedin.com'])->label(false) ?>
              </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12 text-right">
              <?= Html::submitButton('Save Changes', ['class' => 'btn-blue border_radius']) ?>
            </div>
          <?php ActiveForm::end(); ?>
        </div>
      </div>
      <div class="col-md-2 hidden-xs"></div>
      <div class="col-md-5 col-sm-6 col-xs-12 profile-form margin20">
        <h3 class=" bottom30 margin20">Change Your Password</h3>
        <div class="row">
          <?php $form = ActiveForm::begin([
            'id' => 'password-form',
            'enableClientValidation' => true,
            'options' => [
                  'class' => 'callus',
              ],
          ]); ?>
            <!-- <div class="col-sm-4">
              <div class="single-query">
                <label>Current Password:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <?//= $form->field($model, 'password')->passwordInput(['class'=>'keyword-input'])->label(false) ?>
              </div>
            </div> -->
            <div class="col-sm-4">
              <div class="single-query">
                <label>New Password:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <?= $form->field($model, 'new_password')->passwordInput(['class'=>'keyword-input'])->label(false) ?>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="single-query">
                <label>Confirm Password:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <?= $form->field($model, 'confirm_password')->passwordInput(['class'=>'keyword-input'])->label(false) ?>
              </div>
            </div>
            <div class="col-sm-12 text-right">
              <?= Html::submitButton('Save Changes', ['class' => 'btn-blue border_radius']) ?>
            </div>
          <?php ActiveForm::end(); ?>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- agents profile page -->

engine/views/agents/properties.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Agents Properties';
$theme = Url::base().'/assets/castle';
?>

<style type="text/css">
.prop-img {
  width: 360px;
  height: 238px;
}
</style>

<!-- agents properties page -->
<section id="agent-2-peperty" class="my-pro padding_half">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="f-p-links bottom40">
          <li><a href="<?= Url::to(['agents/profile']); ?>"><i class="icon-icons230"></i>Profile</a></li>
          <li><a href="#" class="active"><i class="icon-icons215"></i> My Properties</a></li>
          <li>
          <?php if ($dataProvider->getTotalCount() >= 5) { ?>
            <a href="#" onclick="addAlert()"><i class="icon-icons202"></i> Submit Property</a>
          <?php } else { ?>
            <a href="<?= Url::to(['agents/submit-property']); ?>"><i class="icon-icons202"></i> Submit Property</a>
          <?php } ?>
          </li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="text-uppercase">My Properties</h2>
        <?= Yii::$app->session->getFlash('info');?>
      </div>
    </div>
    <?= \yii\widgets\ListView::widget([
          'id'           => 'agent-property',
          'dataProvider' => $dataProvider,
          'itemView'     => '_property_item',
          'layout'       => '
              {items}
              <div class="row">
                <div class="col-md-12">
                  {pager}
                </div>
              </div>
          ',
          'itemOptions' => [
            'class' => 'container',
          ],
          'emptyText' => '<p>'.\Yii::t('app', 'No results found').'</p>',
          'emptyTextOptions' => ['tag' => 'div', 'class' => 'container text-center'],
          'pager' => [
                'prevPageLabel' => 'Previous',
                'nextPageLabel' => 'Next',
                'maxButtonCount' => 3,
                
                // Customzing options for pager container tag
                'options' => [
                    'tag' => 'ul',
                    'class' => 'pagination justify-content-end',
                    'id' => 'pager-container',
                ],
            ],
      ]); ?>
  </div>
</section>
<!-- agents properties page -->