engine/modules/admin/controllers/NewsController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\PropertyNews;
use app\models\PropertyNewsGallery;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\components\AccessRule;
use app\components\MyFormatter;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * NewsController implements the CRUD actions for PropertyNews model.
 */
class NewsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // 'ruleConfig' => [
                //     'class' => AccessRule::className(),
                // ],
                'only' => ['index', 'create', 'update', 'view', 'remove-image', 'delete', 'upload'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'view', 'remove-image', 'delete', 'upload'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        if ($action->id !== "upload") {
            $this->enableCsrfValidation = false;
        } elseif ($action->id !== "remove-image") {
            $this->enableCsrfValidation = false;
        } else {
            $this->enableCsrfValidation = true;
        }
        // $this->enableCsrfValidation = ($action->id !== "upload");
        return parent::beforeAction($action);
    }

    public function actionUpload()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $error = null;
        $models = [];
        $images = new PropertyNewsGallery();

        $transaction = Yii::$app->db->beginTransaction();
        try {
            $models = $images->handleUploadedImages((int)Yii::$app->request->post('id', 0));
            $transaction->commit();

        } catch (\Exception $e) {
            $error = $e->getMessage() . ' at ' . $e->getFile() . ":" . $e->getLine() . PHP_EOL . $e->getTraceAsString();
            $transaction->rollBack();
        }

        if (!$error && $models) {
            $model = reset($models);
            $file_explode = explode('/', $model->image_path);
            $file_name = $file_explode[4];
            $resp = [
                'initialPreview' => [
                    Yii::getAlias('@web'.$model->image_path),
                ],
                'initialPreviewConfig' => [[
                    'caption' => $file_name,
                    'url' => Url::to(['/agents/remove-image']),
                    'key' => $model->id_property_news_gallery
                ]]
            ];
        } else {
            $resp = ['error' => $error ? $error : ($images->hasErrors() ? $images->getFirstErrors() : 'Unknown')];
        }

        return $resp;
    }

    /**
     * @return array|Response
     */
    public function actionRemoveImage()
    {
        /* allow only ajax calls */
        if (!Yii::$app->request->isAjax) {
            return $this->redirect(['admin/news/create']);
        }

        /* set the output to json */
        Yii::$app->response->format = Response::FORMAT_JSON;

        $imageId = Yii::$app->request->post('key');
        if (empty($imageId)) {
            return ['result' => 'error', 'html' => Yii::t('app', 'Something went wrong...')];
        }

        $imageId = PropertyImage::findOne(['id_image' => $imageId]);
        if (empty($imageId)) {
            return ['result' => 'error', 'html' => Yii::t('app', 'Something went wrong...')];
        }

        // if all images are deleted then the prop is not active anymore
        // $countImages = PropertyImage::find()->where(['id_property' => $imageId->id_property])->count();
        // if ($countImages == 1) {
        //     $prop = Property::find()->where(['id_property' => $imageId->id_property])->one();
        //     $prop->status = Property::STATUS_NOT_ACTIVE;
        //     $prop->save(false);
        // }

        $imageId->delete();

        return ['result' => 'success', 'response' => $imageId];
    }

    /**
     * Lists all PropertyNews models.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionGetalldata()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => PropertyNews::find()
                // ->where(['not in', 'status', ['1']])
                // ->where(['is_approved'=>0])
                ->orderBy(['id_property_news'=>SORT_DESC]),
            'pagination'=>false
        ]);

        $result = [];
        $data = [];
        $i = 1;
        foreach ($dataProvider->getModels() as $value) {
            $nestedData = [];
            $nestedData[] = $i;
            $nestedData[] = $value['title'];
            $nestedData[] = $value->property['title'];
            $nestedData[] = $value->property['location'];
            // $nestedData[] = $value['image_path'];
            $nestedData[] = $value['created_at'];
            $nestedData[] = $value->getStatusLabel();
            $nestedData[] = PropertyNews::getActionButton($value['id_property_news']);

            $data[] = $nestedData;
            $i++;
        }

        $result = array(
            "data" => $data,
        );

        return \yii\helpers\Json::encode($result);
    }

    /**
     * Displays a single PropertyNews model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PropertyNews model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PropertyNews();
        $gallery = new PropertyNewsGallery();

        if ($model->load(Yii::$app->request->post())) {
            $model->id_user = Yii::$app->user->identity->id;
            $model->created_at = date('Y-m-d H:i:s');
            if ($model->save()) {
                $modelGallery = $gallery->handleUploadedImages($model->id_property_news);
                Yii::$app->session->setFlash('info', MyFormatter::success('<strong>Congrats!</strong> Data is successfully saved.'));
                return $this->redirect(['view', 'id' => $model->id_property_news]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'gallery' => $gallery,
        ]);
    }

    /**
     * Updates an existing PropertyNews model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $gallery = new PropertyNewsGallery();
        $uploadedImages = PropertyNewsGallery::find()
            ->where(['id_property_news' => $id])
            ->orderBy('sort_order ASC')
            ->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_property_news]);
        }

        return $this->render('update', [
            'model' => $model,
            'gallery' => $gallery,
            'uploadedImages' => $uploadedImages,
        ]);
    }

    /**
     * Deletes an existing PropertyNews model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->enableCsrfValidation = false;
        $news_gallery = PropertyNewsGallery::deleteAll('id_property_news = :id', [':id' => $id]);
        $news = $this->findModel($id);
        if ($news->delete()) { 
            Yii::$app->session->setFlash('info', MyFormatter::success('<strong>Congrats!</strong> Data is successfully deleted.'));
            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the PropertyNews model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PropertyNews the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PropertyNews::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

engine/modules/admin/views/news/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\Property;

/* @var $this yii\web\View */
/* @var $model app\models\PropertyNews */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="m-portlet">
    <?php $form = ActiveForm::begin([
        'id' => 'property-news-form',
        'enableClientValidation' => true,
        'options' => [
            'class' => 'm-form m-form--fit m-form--label-align-right',
        ],
    ]); ?>
    <div class="m-portlet__body">
        <!-- <div class="form-group m-form__group m--margin-top-10">
            <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-brand alert-dismissible fade show" role="alert">
                <div class="m-alert__icon">
                    <i class="flaticon-exclamation-1"></i>
                    <span></span>
                </div>
                <div class="m-alert__text" style="color: black;">
                    <strong>Attention!</strong> Entries with marks (<span class="required">*</span>) must be filled in.
                </div>
            </div>
        </div> -->
        <div class="form-group m-form__group m--margin-top-10">
            <?= $form->errorSummary($model); ?>
        </div>

        <?php
            $field = $form->field($model, 'id_property', ['options' => ['class' => 'form-group m-form__group row']]);
            $field->template = '{label}<div class="col-lg-6">{input}{error}</div>';
            echo $field->dropDownList(Property::getAllProperty(), ['prompt'=>'-- Choose Property --','class'=>'form-control select'])->label('Property', ['class'=>'col-lg-3 col-form-label']);
        ?>
        <?php
            $field = $form->field($model, 'title', ['options' => ['class' => 'form-group m-form__group row']]);
            $field->template = '{label}<div class="col-lg-6">{input}{error}</div>';
            echo $field->textInput(['maxlength' => 255])->label('Title', ['class'=>'col-lg-3 col-form-label']);
        ?>
        <?php
            $field = $form->field($model, 'description', ['options' => ['class' => 'form-group m-form__group row']]);
            $field->template = '{label}<div class="col-lg-6">{input}{error}</div>';
            echo $field->textarea(['rows' => 6])->label('Description', ['class'=>'col-lg-3 col-form-label']);
        ?>
        <?php
            $field = $form->field($model, 'youtube_1', ['options' => ['class' => 'form-group m-form__group row']]);
            $field->template = '{label}<div class="col-lg-6">{input}{error}</div>';
            echo $field->textInput(['maxlength' => 255])->label('Youtube URL', ['class'=>'col-lg-3 col-form-label']);
        ?>
        <?php
            // $field = $form->field($model, 'youtube_2', ['options' => ['class' => 'form-group m-form__group row']]);
            // $field->template = '{label}<div class="col-lg-6">{input}{error}</div>';
            // echo $field->textInput(['maxlength' => 255])->label('Youtube', ['class'=>'col-lg-3 col-form-label']);
        ?>
        <?php
            $field = $form->field($gallery, 'imagesGallery[]', ['options' => ['class' => 'form-group m-form__group row']]);
            $field->template = '{label}<div class="col-lg-6">{input}{error}</div>';
            $imagesPreview = [];
            $imagesPreviewConfig = [];
            if (isset($uploadedImages)) {
                // sort for images sort_order
                if ($uploadedImages) foreach ($uploadedImages as $key => $image) {
                    $imagesPreview[] = $image->image_path;
                    $imagesPreviewConfig[$key]['caption'] = $image->image_path;
                    $imagesPreviewConfig[$key]['url'] = Url::to(['news/remove-image']);
                    $imagesPreviewConfig[$key]['key'] = $image->id_property_news_gallery;
                }
            }
            echo $field->widget(\kartik\file\FileInput::classname(), [
                'options' => [
                    'multiple' => true,
                    'class' =>'file-loading',
                    'accept' => 'image/*',
                ],
                'pluginOptions' => [
                    'initialPreview'=> $imagesPreview,
                    'initialPreviewConfig' => $imagesPreviewConfig,
                    'initialPreviewAsData' => true, // identify if you are sending preview data only and not the raw markup
                    'initialPreviewFileType' => 'image', // image is the default and can be overridden in config below
                    'deleteUrl' => false,
                    'uploadUrl' => Url::to(['upload']),
                    'uploadAsync' => false,
                    'allowedFileTypes' => ["image"],
                    'showCaption' => false,
                    'showRemove' => true,
                    'showUpload' => false,
                    'showCancel' => false,
                    'browseOnZoneClick' => true,
                    'autoOrientImage' => true,
                    'browseClass' => 'btn btn-info btn-block',
                    'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
                    'browseLabel' =>  'Select Photo',
                    'removeClass' => 'btn btn-default btn-secondary btn-block',
                    'removeIcon' => '<i class="glyphicon glyphicon-trash"></i> ',
                    'removeLabel' =>  'Remove',
                    'fileActionSettings' => [
                        'showUpload' => false,
                        'showDrag' => true,
                        'autoOrientImage' => true,
                        'showRemove' => false,
                    ],
                    'overwriteInitial'=>false,
                    'maxFileCount' => 4,
                ],
                'pluginEvents' => [
                    'filebatchselected' => new \yii\web\JsExpression(
                    'function(event, files) {
                        jQuery(event.currentTarget).fileinput("upload");
                    }')
                ]
            ])->label('Image', ['class'=>'col-lg-3 col-form-label']);
        ?>

        <!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/7TF00hJI78Y" frameborder="0" allowfullscreen></iframe> -->
    </div>
    <div class="m-portlet__foot m-portlet__foot--fit">
        <div class="m-form__actions m-form__actions">
            <div class="form-group m-form__group row">
                <div class="col-lg-4"></div>
                <div class="col-lg-8">
                    <?= Html::submitButton('<span><i class="fa fa-save"></i> <span>Submit</span></span>', ['class' => 'btn btn-info m-btn m-btn--icon m-btn--wide']) ?>
                    <button type="reset" class="btn btn-secondary m-btn m-btn--icon m-btn--wide"><span><i class="fa fa-history"></i> <span>Cancel</span></span></button>
                </div>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

engine/modules/admin/views/news/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\PropertyNews */

$this->title = 'Create Property News';
$this->params['breadcrumbs'][] = ['label' => 'Property News', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="property-news-create">
    <?= $this->render('_form', [
        'model' => $model,
        'gallery' => $gallery,
    ]) ?>
</div>

engine/modules/admin/views/news/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Property News';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="property-news-index">
    <div class="row">
        <div class="col-md-12">
            <?= Yii::$app->session->getFlash('info');?>
            <div class="m-portlet">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-progress">

                        <!-- here can place a progress bar-->
                    </div>
                    <div class="m-portlet__head-wrapper">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon">
                                    <i class="flaticon-envelope"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Data Property News
                                </h3>
                            </div>
                        </div>
                        <div class="m-portlet__head-tools">
                            <?= Html::a('<span><i class="fa fa-plus"></i><span>Add Data</span></span>', ['create'], ['class' => 'btn btn-info m-btn m-btn--icon m-btn--wide m-btn--md m--margin-right-10']) ?>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <table class="table table-striped- table-bordered table-hover" id="tablegrid">
                        <thead>
                            <tr>
                                <th width="10px">#</th>
                                <th width="90px">Title</th>
                                <th width="90px">Property</th>
                                <th width="90px">Location</th>
                                <!-- <th width="50px">Image</th> -->
                                <th width="90px">Created At</th>
                                <th width="40px">Status</th>
                                <th width="80px">#</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

engine/modules/admin/views/news/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\PropertyNews */

$this->title = 'Update Property News: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Property News', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id_property_news]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="property-news-update">

    <?= $this->render('_form', [
        'model' => $model,
        'gallery' => $gallery,
        'uploadedImages' => $uploadedImages,
    ]) ?>

</div>

engine/modules/admin/views/news/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\PropertyNews */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Property News', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>

<div class="row">
    <div class="col-md-12">
        <div class="m-portlet">
            <div class="m-portlet__head">
                <div class="m-portlet__head-progress">

                    <!-- here can place a progress bar-->
                </div>
                <div class="m-portlet__head-wrapper">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon">
                                <i class="flaticon-envelope"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                Detail Property News
                            </h3>
                        </div>
                    </div>
                    <div class="m-portlet__head-tools">
                        <?= Html::a('<span><i class="fa fa-plus"></i><span>Add Data</span></span>', ['create'], ['class' => 'btn btn-info m-btn m-btn--icon m-btn--wide m-btn--md m--margin-right-10']) ?>
                        <?= Html::a('<span><i class="fa fa-edit"></i><span>Update Data</span></span>', ['update', 'id' => $model->id_property_news], ['class' => 'btn btn-success m-btn m-btn--icon m-btn--wide m-btn--md m--margin-right-10']) ?>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <?= Yii::$app->session->getFlash('info');?>
                <div class="table-scrollable">
                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'id_property_news',
                            'id_property',
                            'title',
                            'description:ntext',
                            'slug',
                            'youtube_1',
                            'youtube_2',
                            'id_user',
                            [
                                'label' => 'Status',
                                'format' => 'raw',
                                'value' => $model->getStatusLabel(),
                            ],
                            'created_at',
                        ],
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>